export default {
  id: 'skeleton',
  app_name: 'Basic Redis caching example in Nodejs',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  type: 'Building Block',
  contributed_by: 'Redis Labs',
  repo_url: '',
  download_url: '',
  hosted_url: '',
  quick_deploy: 'false',
  deploy_buttons: [],
  language: ['JavaScript', 'Ruby'],
  redis_commands: ['command1', 'command2', 'command3', 'command4'],
  redis_features: ['header'],
  redis_modules: [],
  app_image_urls: [],
  special_tags: [],
  markdown: '',
  verticals: []
};
